### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-docs#97]
Based on https://twitter.com/dsabar/status/727737356317495297 we have the following new apps:
- http://www.hrpartner.io/
- http://www.letsinduct.me/
- http://www.logbookhq.com/

Would be nice if the examples can be added to the examples.

**Comment by CyberFerret** [comment]
Can add [www.staffstatus.io](http://www.staffstatus.io) to the list too.

More than happy to write up a blog post about any of these if you think it will help with getting the Padrino name out there.

HR Partner is the biggest one I've done to date - around 80 DB tables, and around 21000 lines of Ruby and HAML code.

**Comment by wikimatze** [comment]
Feel free!

**Comment by CyberFerret** [comment]
I notice there is no 'Example' page on the main padrinorb site at the moment.  Is the intent to add one? If so, I am happy to mock up a draft page for approval.

But I would like a general callout to all padrino users to submit their pages here for inclusion - I feel uncomfortable having just my apps on there and would like to be a general showcase of what is possible with Padrino rather than a boast page for my work.

**Comment by wikimatze** [comment]
You can find the examples <http://padrinorb.com/guides/introduction/examples/> and the file to edit under <https://github.com/padrino/padrino-docs/blob/master/guides/01_introduction/03_examples.html.md>.

Good idea with the inclusion.

**Comment by wikimatze** [comment]
All examples are included in the example page except http://www.letsinduct.me/ //cc @CyberFerret
